name: Swift

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Build
      run: swift build -v
